红黑树+小根堆实现的基于优先级的本地缓存
ecodeclub/ecache pull request #20
Opened 2023-09-23 05:46 UTC by KelipuTe

红黑树+小根堆实现的基于优先级的本地缓存

缓存本体用红黑树，数据用缓存结点做一层封装
通过缓存结点可以得到一个权重值出来，这个权重值用小根堆处理

小根堆的结构是，权重作为排序，然后数据用一个优先级结点做一层封装
额外维护一个map，map[权重]优先级结点，解决小根堆查找时需要遍历的问题
小根堆和这个map，做一个封装

小根堆自带asc排序，至于desc排序，我内置了一个 (max int64)/2 作位权重最大值，作差就可以用小根堆实现desc

优先级结点里面有一个map用于保存缓存结点的指针，缓存结点里也会维护一个优先级结点的指针
双向的指针，方便删除缓存或者发生淘汰时，双向的查找

lru，lfu，内存大小，自定义优先级，暂时没想到一个统一的抽象能把这四个都塞进去

ekit 那边实现了一个小根堆结构，同时需要把internal里面的红黑树也放出来

2023-09-25 06:31 UTC, KelipuTe commented
..\..\ekit\queue\concurrent_array_blocking_queue.go:21:2: missing go.sum entry for module providing package golang.org/x/sync/semaphore (imported by github.com/ecodeclub/ekit/queue); to add:
	go get github.com/ecodeclub/ekit/queue@v0.0.7
提示要执行go get，gomod和gosum变了，多了个golang.org/x/sync

2023-09-25 06:32 UTC, KelipuTe commented
基本没啥大改动，优先级队列的peak、enqueue、dequeue可以无缝替换之前小根堆那几个操作

2023-09-25 11:41 UTC, flycash commented
要先等 ekit 那边暴露了优先级队列，直接使用那边的优先级队列。

2023-09-26 03:46 UTC, flycash reviewed
你是不是没有处理过期时间？支持过期？
这个实现看起来没特别大的问题，但是太复杂了。我想到一个比较简单的方式，可以简化实现，并且降低本身内存结构的消耗。

也就是保持两个结构，一个红黑树，放数据；一个是优先级队列，放优先级信息。

运作方式就是：
- 过期时间控制采用懒惰 + 定时删除的策略。也就是在 GET 的时候会检测有没有过期，如果过期了的话直接返回不存在，同时执行红黑树上的删除。
- 红黑树上的删除，就是把 Data 字段（也就是用户的数据）重置为 nil，对应的 key 也置为 nil。但是优先级队列上的不动，或者说是把这个节点标记位已经被删除。
- 这时候，这种被删除的节点就只存在优先级队列了。
- 当触发了淘汰策略的时候，就从优先级队列里面淘汰元素。遵循这种逻辑：不断从队列里面取出来元素，如果节点本身被标记位已经删除了，就下一个；否则就是真的淘汰了一个节点。
- 启动一个 goroutine，遍历红黑树，懒惰删除过期数据。

2023-09-26 03:46 UTC, flycash commented on memory/rbtree_client.go
> +	orderByASC            bool           //true=按权重从小到大排;按false=权重从大到小排;
我们不管这种事情，永远默认是优先级最小的淘汰掉。对于用户来说，他自己取反就可以了，我们不关心。这样可以省去很多不必要的麻烦事。

2023-09-26 03:46 UTC, flycash commented on memory/rbtree_client.go
> +func SetCacheLimit(cacheLimit int) option.Option[RBTreeClient] {
一般 Option 模式都是各种 WithXXXX

2023-09-26 03:46 UTC, flycash commented on memory/rbtree_client.go
> +type RBTreeClient struct {
改名叫做 RBPriorityTreeCache，一般涉及到远程通信才会引入客户端或者服务端的说法

2023-09-26 03:46 UTC, flycash commented on memory/cache.go
> +func NewCache(client ecache.Cache) *Cache {
这个看起来不就是多余的吗？

2023-09-26 03:46 UTC, flycash commented on memory/cache.go
> +func NewCache(client ecache.Cache) *Cache {
我说整个 Cache

2023-09-26 03:46 UTC, flycash commented on memory/cache_priority.go
> +	GetPriorityWeight() int64
纠正一下全部的命名，就是我们这里只有 Priority 的概念，但是没有 Weight 的概念。或者说，Priority 就是 Weight

2023-09-26 03:46 UTC, flycash commented on memory/cache_priority.go
> +type CachePriority struct {
这个是内部结构，做成私有的。

2023-09-26 03:46 UTC, flycash commented on memory/cache_priority.go
> +type CachePriority struct {
对应的方法也全部做成私有的。

2023-09-26 03:46 UTC, flycash commented on memory/cache_priority.go
> +	priorityWeightMap map[int64]*priorityNode             //方便快速找某个权重值的结点
我倒是能够理解这个字段的作用，但是问题是，优先级是可以相同的。也就是我有两个 key-value，但是我 key 其实是不同的，但是优先级是一样的，

2023-09-26 03:46 UTC, flycash commented on memory/cache_priority.go
> +func (cp *CachePriority) findPriorityNodeByPriorityWeight(priorityWeight int64) (*priorityNode, error) {
貌似只被一个节点用到了，那么可以考虑直接返回 ok ?

2023-09-26 03:46 UTC, flycash commented on memory/rbtree_client.go
> +			}
把这段逻辑封装起来，代表就是淘汰一个节点。

2023-09-26 10:58 UTC, KelipuTe commented on memory/rbtree_client.go
> +	orderByASC            bool           //true=按权重从小到大排;按false=权重从大到小排;
这地方是为了把lru，lfu，内存大小正序倒序淘汰伪装成优先级的时候用的。
只有优先级一种策略的话，如果用户传进来的具体数据实现了Priority接口那直接算优先级的数值就完了。
defaultPriorityWeight直接去掉全部默认0倒是没有太大的问题。

但是如果要实现lru和lfu，那么这两个策略都和get这个动作有关系，和用户传进来的具体数据没关系。
这个时候计算优先级的地方就需要分情况讨论了，所以有的priorityType这个字段

maxPriorityWeight和orderByASC这两个字段是支持按内存大小正序倒序用的，实现了Priority接口的数据可以用户自己定义怎么算内存，但是int这种的就没办法了。
这两个去掉也可以，基本类型都是0，用户如果想大对象先淘汰就自己实现Priority接口然后给内存大小取反，小对象先淘汰就给正常的内存大小就行。

但是这么看来priorityType这个好像绕不过去，lru和lfu这两种策略和优先级策略作用的对象不同

2023-09-26 11:03 UTC, KelipuTe commented on memory/cache_priority.go
> +	priorityWeightMap map[int64]*priorityNode             //方便快速找某个权重值的结点
这地方本来是的设计是用优先级数值构造结点，相同优先级的数据都放到一起，用来支持随机删除缓存的时候一并删掉优先级数据用的，如果换成上面的标记策略那这里也可以省掉，就一个优先级队列就可以了

2023-09-27 10:18 UTC, KelipuTe commented
1、数据结构简化之后，逻辑确实简单多了。

2、lru和lfu这两种策略和优先级策略作用的对象不同，还是上面那个问题，priorityType这个字段我没想到好办法绕过去。

3、定时删除过期数据那里，怎么设置时间间隔呢？sleep一秒还是无限循环中间不停，不停总有点费cpu的感觉。

4、优先级队列的初始化大小还有set用的MapSet的初始化大小那两个init参数，option模式好像也解决不了用户不传的问题，还是说这里默认传个0也是没太大问题的

2023-09-27 10:29 UTC, flycash reviewed
创建一个 priority 的子包，然后把这个代码丢进去。而后，额外提供两个 New 方法，NewLRUTreeCache 和 NewLFUTreeCache。这样，就可以删除 WithPriorityType 这个选项。用户不能指定。用户通过 NewLRU 或者 LFU 创建的就是对应的缓存，而直接通过 RBTreePriority 创建的，就是普通的优先级。

2023-09-27 10:29 UTC, flycash commented on memory/rbtree_priority_cache.go
> +	ErrOnlyNumCanDecrBy  = errors.New("ecache: 只有数字类型的数据，才能执行 DecrBy")
不着急做成公有的，可以都保持私有的。

2023-09-27 10:30 UTC, flycash commented
有咩有可能提供一个 PriorityStrateg，把内部和 LRU，LFU 的操作都封装到里面？比如说更新优先级，或者获取优先级。

2023-10-04 15:07 UTC, KelipuTe commented
把之前保存优先级数据的结构扩展了一下，把和优先级有关系的操作都从缓存结构里面抽出来整到里面去了，
但是lru和lfu那里，优先级是受缓存结构的get动作影响的，所以需要单独提供一个方法给缓存结构判断要不要重新设置优先级

2023-10-05 11:55 UTC, flycash commented
我发现一个新的问题，就是在 ekit 的优先级队列里面，调整优先级并不会触发堆结构调整。这是不是说，你这里调整了优先级之后，其实效果不对？

2023-10-05 11:55 UTC, flycash commented
应该是咩有效果。

2023-10-05 12:07 UTC, flycash commented
如果是没有效果的话，就要把 LRU 和 LFU 删掉，后面再单独各自写一个。

2023-10-05 13:50 UTC, KelipuTe commented
ekit 的那个优先级队列直接改优先级数值是没用的。
我这里的逻辑是删掉之前的数据（变空结点，就留着不动），然后补一个新的结点（这里会触发小根堆重新排序）。
然后在触发淘汰的时候，再去处理优先级队列里面的空结点。
lru和lfu单独写了测试，这么操作是有用的。

2023-10-06 02:50 UTC, flycash requested changes
我感觉这种实现太复杂了，性价比不高。这里要改为：
1. 不要支持 LRU 和 LFU，后面单独提供新的实现。
2. 认为节点的优先级不会发生改变。即便用户乱搞，改变了也没关系，因为我们说按照优先级淘汰，就算是淘汰错了，也没有特别大的影响。从我之前使用优先级淘汰策略来看，的确不存在修改的场景。
3. 对应的，这里面的 priority _node 和 priority_strategy 应该都用不上了

对了，把现有的代码放好，说不定将来我又需要了，还能找回来。

2023-10-07 15:22 UTC, KelipuTe commented
这么搞就是优先级的代码和缓存的代码揉到一起去了，优先级队列里面装的直接就是缓存结点，缓存结点需要额外存一下本身的优先级。
缓存过期需要删除的时候，因为优先级队列不支持随机删除，所以采用的是清空结点上的数据，结点不动的策略。等到触发淘汰的时候再说。

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_cache_node.go
> +	rbTreeCacheNodeTypeNum             //int64，给IncrBy和DecrBy用
这些类型其实是用不上的。首先是所有的都参与淘汰，没有说不参与淘汰的。如果一个键值对本身没有优先级，那么就是默认优先级，在这种情况下，就用默认优先级参与淘汰。

而后面的不管是 List，Set 还是 Num 要求的都是对对应类型进行断言，断言能成功就可以。

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +	cacheLimit    int                                    //优先级淘汰的键值对数量限制，默认0，表示没有限制
默认给它一个 int32 的最大值，也差不多近似于没有限制了。

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +	cacheLimit    int                                    //优先级淘汰的键值对数量限制，默认0，表示没有限制
0 这种语义处理起来又是 if-else

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_cache_node.go
> +type rbTreeCacheNode struct {
在这里加一个标记位，代表是否被淘汰了，也就是 deleted

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +		node.value = val
在 node 上定义一个 replace 方法，设置新的 val 和 expiration。

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +		r.deleteCacheNodePriority(checkNode) //移除优先级数据
这边在 node 上定义一个叫做 truncate 的方法，然后清空对应的数据。

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +func (r *RBTreePriorityCache) calculatePriority(node *rbTreeCacheNode) int64 {
在 RBTree 里面维持一个 defaultPriority 字段。

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +func (r *RBTreePriorityCache) autoClean() {
这里是不是可以直接使用 time.Ticker？

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +		time.Sleep(time.Second)
在使用 time.Ticker 之后，这个间隔时间要做成参数。

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +	//这里不需要加锁，因为触发淘汰的时候肯定是走了set逻辑，已经锁过了
在注释里面加上：调用该方法必须先获得锁。

2023-10-08 03:58 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +		if topNode.key == "" {
使用标记位，因为有时候用户确实会使用空字符串作为 key。

2023-10-09 01:39 UTC, KelipuTe commented on memory/priority/rbtree_cache_node.go
> +	rbTreeCacheNodeTypeNum             //int64，给IncrBy和DecrBy用
去掉结点类型的话，有一个问题啊，如果先 sadd("key1","1","2") ，然后接着 set("key1","a")这种情况咋办。调用sadd,lpush,IncrBy 这些特殊的方法的时候，确实可以用断言判断any是不是可以操作的类型。但是调set的时候呢。直接覆盖？

2023-10-10 06:51 UTC, KelipuTe commented on memory/priority/rbtree_priority_cache.go
> +		time.Sleep(time.Second)
这种初始化参数怎么定义呢，之前的优先级队列和mapset那里也有两个类似的初始化参数，用 option 模式并不能限制用户不填，但是内部 time.NewTicker() 又一定需要一个非0值去初始化，我也不知道初始化定多少合适，这种场景咋办

2023-10-10 11:57 UTC, flycash reviewed
nice，只剩下一点点小问题了

2023-10-10 11:57 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +	if node.value == val {
这个逻辑删掉。因为目前 Redis 那边的语义是 key 存在就什么也不做。所以大家都养成了这么一种预期，就是 KEY 存在就啥也不做，过期时间也不会更新。

2023-10-10 11:57 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +	return
这个 return 已经没有意义了

2023-10-10 11:57 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +	successNum := 0
直接声明为 int64，省去类型转化

2023-10-10 11:57 UTC, flycash commented on memory/priority/rbtree_priority_cache.go
> +	successNum := 0
类似，声明成 int64

2023-10-11 11:49 UTC, flycash approved these changes
后续一些小地方我再琢磨琢磨，自己改进。非常感谢

2023-10-11 11:49 UTC, flycash commented
大哥，解决冲突！

2023-10-13 12:31 UTC, merged