[feat](新增set实现) 补充lru set实现
ecodeclub/ecache pull request #22
Opened 2023-10-04 16:03 UTC by ogreks

2023-10-05 12:05 UTC, flycash requested changes

2023-10-05 12:05 UTC, flycash commented on memory/lru/cache.go
> +		s, err := set.NewTreeSet[ecache.Value](func(src ecache.Value, dst ecache.Value) int {
这个地方有点问题，因为在这个方法里面，要比较的是大于、小于或者等于。所以你这里不能这么写。

要想万无一失还是比较难的，这里我们用一种比较朴素的方法，就是将这个做成一个参数，在初始化的时候用户可以用 Option 模式来传入这个参数。

如果没有传入这个参数，我们直接使用 fmt.Sprint("%v") 这种做法，比较字符串。

2023-10-05 12:05 UTC, flycash commented on memory/lru/cache.go
> +		s, err := set.NewTreeSet[ecache.Value](func(src ecache.Value, dst ecache.Value) int {
类似于:
```go
type Cache struct {
    // ... 其它字段
    setComparator ekit.Comparator
}
```

2023-10-05 12:05 UTC, flycash commented on memory/lru/cache.go
> +	s, ok := result.Val.(*set.TreeSet[ecache.Value])
我觉得，直接存储原始数据，只有在 GET 方法的时候才返回 Value。因为本身 ecache.Value 只是为了简化用户操作的。

2023-10-05 12:05 UTC, flycash commented on memory/lru/cache.go
> +	s, ok := result.Val.(*set.TreeSet[ecache.Value])
你看看 List 那边，保持存储的时候就只存储原始数据。

2023-10-08 04:00 UTC, flycash requested changes

2023-10-08 04:00 UTC, flycash commented on memory/lru/cache.go
> +		s, err := set.NewTreeSet[any](c.setComparator)
我琢磨来琢磨去，这个地方还是用 MapSet 吧，这样子我们就不需要关心如何比较的问题了。用户只要自己使用的时候小心传入一个在 GO 语言层面上是可比较的就可以。

2023-10-10 14:41 UTC, ogreks commented on memory/lru/cache.go
> +		s, err := set.NewTreeSet[any](c.setComparator)
已经修改，但是MapSet需要一个size，我预设了他跟redis的set保持一致

2023-10-11 04:37 UTC, flycash requested changes

2023-10-11 04:37 UTC, flycash commented on memory/lru/cache.go
> +		s := set.NewMapSet[any](2 ^ 32 - 1)
我草，不要设置那么大，会寄了的。你直接设置为 8 就差不多了

2023-10-11 04:37 UTC, flycash commented on memory/lru/cache.go
> +		s := set.NewMapSet[any](2 ^ 32 - 1)
你把这个括号里面的遍历和后面的遍历都整合在一起，只需要写一遍就可以。
相当于，要么创建出来一个 Set，要么类型断言出来一个 Set，而后遍历添加

2023-10-12 07:28 UTC, flycash approved these changes

2023-10-12 07:28 UTC, merged